### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/Agents_i2b#10]
Test coverage can be improved, specially testing better the domain classes. All the information about which classes can we test more can be seen here: https://codecov.io/gh/Arquisoft/Agents_i2b/branch/master

**Comment by carmee-en** [comment]
Currently trying to find a way to test bad logins via exception throwing (to make use of AgentNotFoundException). 

Will update soon.

**Update**: it doesn't seem possible. At least not via "@"Test(expected= ...) . Anyway I found the html status for bad logins should be 401 instead of 404.

**Comment by alejgh** [comment]
I think 86% coverage is good enough for this project. There is no need to make complicated tests or modify the classes just to get an extra 4%, so I think we can close this issue.
Thanks for the effort though 👍.
