### ISSUE TITLE
Include a user manual in the Wiki

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/Agents_i2b#2]
As the title says, it would be great if we add a new entry in the wiki containing a user manual, with instructions about how to use our module for a new user. This entry could include:
* How to execute the project from the command line (mvn spring-boot:run).
* How to set up mongodb (we can reuse most of the documentation from last year).
* How to use the 'advanced rest client' tool to send a post request to our module.
* Brief overview of the web interface available to use.
* Other info...

**Comment by ulitol97** [comment]
I'll take care of the user manual in the wiki

**Comment by ulitol97** [comment]
Wiki entries updated.
Created a branch to upload and store captions used in the user manual.

**Comment by ulitol97** [comment]
Closed incidentally.
